fix xcode issue with _Symbols

diff --git a/packages/reown_appkit/example/base/ios/fastlane/Fastfile b/packages/reown_appkit/example/base/ios/fastlane/Fastfile
--- a/packages/reown_appkit/example/base/ios/fastlane/Fastfile
+++ b/packages/reown_appkit/example/base/ios/fastlane/Fastfile
@@ -102,12 +102,21 @@ platform :ios do
       export_method: "app-store",
       clean: true,
       xcargs: "PROJECT_ID='#{options[:project_id]}'",
-      # output_directory: "build/ios", # Explicitly set output directory
-      # archive_path: "build/ios/Runner.xcarchive" # Explicitly set archive path
+      output_directory: "build", # Explicitly set output directory
+      include_symbols: false,
     )
 
-    # # Add step to remove macOS hidden files from the archive
-    # sh("find ../build/ios/Runner.xcarchive -name '._*' -exec rm -f {} \\;")
+    # Add step to remove macOS hidden files from the archive
+    sh('''
+      IPA_PATH="../build/Runner.ipa"
+
+      if [ -f "$IPA_PATH" ]; then
+        echo "Checking for unwanted files like ._Symbols in $IPA_PATH"
+        unzip -l "$IPA_PATH" | grep ._Symbols && zip -d "$IPA_PATH" ._Symbols/ || echo "No ._Symbols found"
+      else
+        echo "IPA not found at $IPA_PATH"
+      fi
+    ''')
 
     _app_version = "3.0.0" #"options[:app_version]"
     
