Implementation of Events SDK to cover LINK MODE related events (#140)
* Fix issue of app hanging where no metadata url was given

* Implemented events SDK in Core SDK

* refactor on appkit side

* Changed headers into query params

* prepared versions

* minor change

* implemented events storage and batch send

* implemented events storage and batch send

* Rollback some files

* minor change

* fix xcode issue with _Symbols

* delete unneeded file

* fixes for Jakubs reports

* minor changes

* Minor change

diff --git a/packages/reown_walletkit/example/ios/fastlane/Fastfile b/packages/reown_walletkit/example/ios/fastlane/Fastfile
--- a/packages/reown_walletkit/example/ios/fastlane/Fastfile
+++ b/packages/reown_walletkit/example/ios/fastlane/Fastfile
@@ -100,10 +100,22 @@ platform :ios do
       scheme: _flavor,
       export_method: "app-store",
       clean: true,
-      xcargs: "PROJECT_ID='#{options[:project_id]}'"
+      xcargs: "PROJECT_ID='#{options[:project_id]}'",
+      output_directory: "build", # Explicitly set output directory
+      include_symbols: false,
     )
 
-    _app_version = "3.0.0" #"options[:app_version]"
+    # Add step to remove macOS hidden files from the archive
+    sh('''
+      IPA_PATH="../build/Runner.ipa"
+
+      if [ -f "$IPA_PATH" ]; then
+        echo "Checking for unwanted files like ._Symbols in $IPA_PATH"
+        unzip -l "$IPA_PATH" | grep ._Symbols && zip -d "$IPA_PATH" ._Symbols/ || echo "No ._Symbols found"
+      else
+        echo "IPA not found at $IPA_PATH"
+      fi
+    ''')
     
     _app_version = "3.0.0" #"options[:app_version]"
     
